# This builds multiple projects
# 1. the "one-app" of the Book Monkey2 - all components are tied togehter in one big app with explanations
# 2. single apps for each iteration/increment

language: node_js

node_js:
  - '4.2'
  
env:
  global:
    # node-gyp: Node.js v4 (or io.js v3) compiler requirements
    # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
    - CXX=g++-4.8  
    - GITHUB_ORG=https://REPO_USER_AND_PASS@github.com/book-monkey2-build
  matrix:
    - NAME=one-app
    - NAME=iteration-1-book-details BLUEPRINT=src/client/app/book-monkey/iteration-1/book-details
    - NAME=iteration-1-book-list BLUEPRINT=src/client/app/book-monkey/iteration-1/book-list

install:
  - npm install

script:
  - echo $NAME

  # [1] one-app: fills /dist folder and adds CNAME file as well as 404 file for gh-pages
  # TODO: npm run ng test  
  - if [ "$NAME" == "one-app" ]; then 
      npm run ng build;
      echo "book-monkey2.angular2buch.de" > dist/CNAME;
      cp dist/index.html dist/404.html;
    fi

  # [2] create multiple single apps
  - if [ "$NAME" != "one-app" ]; then 
      cd ..;
      mkdir TMP;
      cd TMP || exit;
      node "$TRAVIS_BUILD_DIR/node_modules/angular-cli/bin/ng" new BookMonkey;
      cd "$TRAVIS_BUILD_DIR" || exit;
      cp -rf "$BLUEPRINT" ../TMP/BookMonkey/src/client/app;
    fi
  
deploy:
  # [1] one-app: send compiled version to gh-pages
  - if [ "$NAME" == "one-app" ]; then 
      npm run ng -- ghpages --repo="$GITHUB_ORG/$NAME.git" --name="The Buildbot" --email=buildbot@angular2buch.de;
    fi

  # [2] one-app: send uncompiled version to master
  - if [ "$NAME" != "one-app" ]; then 
      npm run ng -- ghpages --repo="$GITHUB_ORG/$NAME.git" --name="The Buildbot" --email=buildbot@angular2buch.de --dir=../TMP/BookMonkey --branch=master;
    fi



# ---- boilerplate ----

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# a build will finish as soon as a job has failed      
matrix:
  fast_finish: true       
  
#only building specific branches  
branches:
  only:
    - master
    - refactoring-all-it