language: node_js

node_js:
  - '4.2'

install:
- npm install

script:
- npm run ng build --environment=production
- echo "book-monkey2.angular2buch.de" > dist/CNAME
- echo -e "---\npermalink: /index.html\n---" > dist/404.md
- npm run ng -- ghpages --repo=https://REPO_USER_AND_PASS@github.com/Angular2Buch/book-monkey2-public.git --name="The Buildbot" --email=buildbot@angular2buch.de

# node-gyp: Node.js v4 (or io.js v3) compiler requirements
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8