language: node_js

node_js:
  - '4.0'

install:
- npm install

script:
- npm run ng build --environment=production
- echo "book-monkey2.angular2buch.de" > dist/CNAME
- npm run ng ghpages --repo=https://REPO_USER_AND_PASS@github.com/Angular2Buch/book-monkey2-public.git --name="The Buildbot" --email=buildbot@angular2buch.de
