# This builds multiple projects
# [1] the "one-app" of the Book Monkey2 - all components are tied togehter in one big app with explanations
# [2] single apps for each iteration/increment

language: node_js

node_js:
  - 6.9.1

cache:
  directories:
  - node_modules

env:
  global:
    # node-gyp: Node.js v4 (or io.js v3) compiler requirements
    # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
    - CXX=g++-4.8
    - GITHUB_ORG="https://GH_TOKEN@github.com/book-monkey2-build"
    - GITHUB_NAME="The Buildbot"
    - GITHUB_EMAIL="buildbot@angular2buch.de"
  matrix:
    # remember: each new app requires a new CNAME entry to book-monkey2-build.github.io
    - NAME="one-app"
    - NAME="iteration-1-components"            BLUEPRINT="src/app/book-monkey/iteration-1/components"
    - NAME="iteration-1-property-bindings"     BLUEPRINT="src/app/book-monkey/iteration-1/property-bindings"
    - NAME="iteration-1-event-bindings"        BLUEPRINT="src/app/book-monkey/iteration-1/event-bindings"

    - NAME="iteration-2-di"                    BLUEPRINT="src/app/book-monkey/iteration-2/di"
    - NAME="iteration-2-navigation"            BLUEPRINT="src/app/book-monkey/iteration-2/navigation"

    - NAME="iteration-3-http"                  BLUEPRINT="src/app/book-monkey/iteration-3/http"

    - NAME="iteration-4-template-driven-forms" BLUEPRINT="src/app/book-monkey/iteration-4/template-driven-forms"
    - NAME="iteration-4-reactive-forms"        BLUEPRINT="src/app/book-monkey/iteration-4/reactive-forms"
    - NAME="iteration-4-custom-validation"     BLUEPRINT="src/app/book-monkey/iteration-4/custom-validation"

    - NAME="iteration-5-pipes"                 BLUEPRINT="src/app/book-monkey/iteration-5/pipes"
    - NAME="iteration-5-directives"            BLUEPRINT="src/app/book-monkey/iteration-5/directives"

    - NAME="iteration-6-modules"               BLUEPRINT="src/app/book-monkey/iteration-6/modules"
    - NAME="iteration-6-lazy-loading"          BLUEPRINT="src/app/book-monkey/iteration-6/lazy-loading"
    - NAME="iteration-6-guards"                BLUEPRINT="src/app/book-monkey/iteration-6/guards"
    - NAME="iteration-6-resolver"              BLUEPRINT="src/app/book-monkey/iteration-6/resolver"

install:
  - npm i --silent -g angular-cli@1.0.0-beta.25.5; npm i --silent -g angular-cli-ghpages;

script:
  - echo "*** BUILDING $NAME ***"

  # [1] one-app:
  # - fills /dist folder and adds CNAME file as well as 404 file for gh-pages
  # - sends compiled version to gh-pages
  # TODO: npm run ng test
  - if [ "$NAME" == "one-app" ]; then
      ng build --prod --aot --no-vendor-chunk;

      echo "book-monkey2.angular-buch.com" > dist/CNAME;
      cp dist/index.html dist/404.html;

      ngh --repo="$GITHUB_ORG/$NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL";
    fi

  # [2] single apps (mini monkeys)
  # - creates multiple single apps by copying file content around
  # - sends uncompiled version to master
  - if [ "$NAME" != "one-app" ]; then

      export NEW_BOOKMONKEY="$TRAVIS_BUILD_DIR/../TMP/BookMonkey";

      cd ..;
      mkdir TMP;
      cd TMP || exit;

      ng new BookMonkey --routing --prefix=bm --skip-npm;
      cd "$NEW_BOOKMONKEY" || exit;
      mkdir -p src/{domain};

      rm -rf .git;
      rm -rf src/app/*;

      cp -f "$TRAVIS_BUILD_DIR/package.mm.json" package.json;
      npm i --silent;


      cd "$TRAVIS_BUILD_DIR" || exit;

      cp -f angular-cli.json                     "$NEW_BOOKMONKEY/";
      cp -f src/assets                           "$NEW_BOOKMONKEY/src/assets/";
      cp -rf "$TRAVIS_BUILD_DIR/$BLUEPRINT/."    "$NEW_BOOKMONKEY/src/app/";


      echo "body { margin:30px; }" > "$NEW_BOOKMONKEY/src/styles.css";

      SEARCH=();
      REPLACE=();
        SEARCH[0]="import { CommonModule } from '@angular/common'";
        REPLACE[0]="import { BrowserModule } from '@angular/platform-browser'";

        SEARCH[1]="import { AppRoutingModule } from './app-routing.module.one-app'";
        REPLACE[1]="import { AppRoutingModule } from './app-routing.module'";

        SEARCH[2]="CommonModule";
        REPLACE[2]="BrowserModule";

        for i in "${!SEARCH[@]}";
        do sed -i "s|${SEARCH[$i]}|${REPLACE[$i]}|g" "$NEW_BOOKMONKEY/src/app/app.module.ts";
        done;
        unset SEARCH; unset REPLACE;

        rm -f "$NEW_BOOKMONKEY/src/app/app-routing.module.one-app.ts";

        SEARCH[0]="app/book-monkey/iteration-6/lazy-loading/";
        SEARCH[1]="app/book-monkey/iteration-6/guards/";
        SEARCH[2]="app/book-monkey/iteration-6/resolver/";
        for i in "${!SEARCH[@]}";
        do sed -i "s|${SEARCH[$i]}|app/|g" "$NEW_BOOKMONKEY/src/app/app-routing.module.ts";
        done;

        sed -i "s|export const routes|const routes|g" "$NEW_BOOKMONKEY/src/app/app-routing.module.ts";

      find $NEW_BOOKMONKEY/src -name "*.snippet" -type f -delete;
      find $NEW_BOOKMONKEY/src -name "*delete_me*" -type f -delete;

      echo "*** DIRECTORY LISTING OF $NEW_BOOKMONKEY ***";
      ls -a "$NEW_BOOKMONKEY";

      ngh --repo="$GITHUB_ORG/$NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --dir=../TMP/BookMonkey --branch=master;
    fi

  # [2] single apps:
  # - compiles single apps
  # - sends them to gh-pages
  - if [ "$NAME" != "one-app" ]; then
      cd "$NEW_BOOKMONKEY/";

      npm i --silent;
      ng build -dev;

      echo "$NAME.angular-buch.com" > dist/CNAME;
      cp dist/index.html dist/404.html;

      ngh --repo="$GITHUB_ORG/$NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL";
    fi

# ---- boilerplate ----

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# a build will finish as soon as a job has failed
matrix:
  fast_finish: true

#only building specific branches
branches:
  only:
    - master
